name: dart_smb2_example
description: Demonstrates how to use the dart_smb2 plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  dart_smb2:
    path: ../
  shared_preferences: ^2.5.5
  flutter_riverpod: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  macos:
    generate: true
  windows:
    generate: true
  image_path: "assets/dart_smb2.png"
  min_sdk_android: 21
